apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
  labels:
    app: flask-todo-app
spec:
  type: NodePort
  selector:
    app: flask-todo-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
    name: http

